# Generated by Django 5.1.4 on 2024-12-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('semail', models.EmailField(default='student@123gmail.com', max_length=254)),
                ('sphoneno', models.IntegerField()),
                ('senrollno', models.IntegerField()),
                ('sadddate', models.DateField()),
                ('sfees', models.BooleanField(default=False)),
            ],
        ),
    ]
