# Generated by Django 5.1.4 on 2024-12-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmission',
            name='sfees',
        ),
        migrations.AlterField(
            model_name='addmission',
            name='sadddate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
