# Generated by Django 5.1.4 on 2024-12-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_addmission_sadddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='user@gmail.com', max_length=254)),
                ('phno', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
    ]
