# Generated by Django 5.1.4 on 2024-12-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmission',
            name='paid_fees',
            field=models.BooleanField(default=False),
        ),
    ]
